name: Fetch pcm-dpc/COVID-19

on:
  push:
  pull_request:
  schedule:
    - cron:  '30 20 * * *'
  workflow_dispatch:

jobs:
  test:
    name: Fetch and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install pytest~=6.2.5 pytest-lazy-fixture~=0.6.3

    - name: Run test
      run: pytest
